[package]
name = "fish"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
colored = "3.0.0"
easy-repl = "0.2.1"
rand = "0.9.2"
strum = "0.27"
strum_macros = "0.27"
num-rational = "0.4"
